#!/bin/bash
# Pre-Write Check Script
# Validates content before it gets written to files
# Outputs structured JSON with severity levels

TOOL_INPUT="$1"

# Parse file path from tool input (JSON format expected)
FILE_PATH=$(echo "$TOOL_INPUT" | grep -oE '"file_path"\s*:\s*"[^"]+' | sed 's/.*"//' || echo "")

# Also try alternative JSON key names
if [ -z "$FILE_PATH" ]; then
  FILE_PATH=$(echo "$TOOL_INPUT" | grep -oE '"path"\s*:\s*"[^"]+' | sed 's/.*"//' || echo "")
fi

if [ -z "$FILE_PATH" ]; then
  # Allow if we can't parse (let the actual tool handle validation)
  echo '{"hook":"pre-write-check","decision":"allow","status":"pass","issues":[]}'
  exit 0
fi

# Check for protected directories
PROTECTED_DIRS=("node_modules" ".git" "dist" "build" "__pycache__" ".venv" "vendor" ".next" "coverage")

for dir in "${PROTECTED_DIRS[@]}"; do
  if echo "$FILE_PATH" | grep -qE "(^|/)$dir(/|$)"; then
    echo "{\"hook\":\"pre-write-check\",\"decision\":\"block\",\"status\":\"error\",\"severity\":\"block\",\"issues\":[{\"type\":\"protected_dir\",\"file\":\"$FILE_PATH\",\"message\":\"Cannot write to protected directory: $dir\",\"suggestion\":\"Choose a different location outside of $dir\"}]}"
    exit 0
  fi
done

# Check for system files
SYSTEM_PATHS=("/etc/" "/usr/" "/bin/" "/sbin/" "/var/" "/root/" "/sys/" "/proc/")

for sys in "${SYSTEM_PATHS[@]}"; do
  if echo "$FILE_PATH" | grep -qE "^$sys"; then
    echo "{\"hook\":\"pre-write-check\",\"decision\":\"block\",\"status\":\"error\",\"severity\":\"block\",\"issues\":[{\"type\":\"system_path\",\"file\":\"$FILE_PATH\",\"message\":\"Cannot write to system path: $sys\",\"suggestion\":\"This is a system directory and should not be modified\"}]}"
    exit 0
  fi
done

# Check for sensitive file patterns
SENSITIVE_PATTERNS=(".env" ".secret" "credentials" "password" "private_key" "id_rsa" "api_key" "token")

for pattern in "${SENSITIVE_PATTERNS[@]}"; do
  if echo "$FILE_PATH" | grep -qi "$pattern"; then
    echo "{\"hook\":\"pre-write-check\",\"decision\":\"warn\",\"status\":\"warning\",\"severity\":\"ask\",\"issues\":[{\"type\":\"sensitive_file\",\"file\":\"$FILE_PATH\",\"message\":\"Writing to potentially sensitive file matching pattern: $pattern\",\"suggestion\":\"Verify this file should contain secrets and won't be committed to version control\"}]}"
    exit 0
  fi
done

# Check for common auto-generated files
AUTO_GENERATED=("package-lock.json" "yarn.lock" "pnpm-lock.yaml" "Cargo.lock" "poetry.lock" "Pipfile.lock")

for pattern in "${AUTO_GENERATED[@]}"; do
  if echo "$FILE_PATH" | grep -qE "(^|/)$pattern$"; then
    echo "{\"hook\":\"pre-write-check\",\"decision\":\"warn\",\"status\":\"warning\",\"severity\":\"suggest\",\"issues\":[{\"type\":\"auto_generated\",\"file\":\"$FILE_PATH\",\"message\":\"This file is typically auto-generated by package managers\",\"suggestion\":\"Let the package manager update this file instead of editing directly\"}]}"
    exit 0
  fi
done

# All checks passed
echo '{"hook":"pre-write-check","decision":"allow","status":"pass","issues":[]}'
exit 0
