#!/bin/bash
# install-git-hooks.sh - Install git hooks for sanitization

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOOKS_DIR="$(git rev-parse --git-dir 2>/dev/null)/hooks"

if [ ! -d "$HOOKS_DIR" ]; then
    echo "Error: Not in a git repository"
    exit 1
fi

echo "Installing git hooks..."

# Pre-commit hook
cat > "$HOOKS_DIR/pre-commit" << 'EOF'
#!/bin/bash
# Auto-generated by Claude Bootstrap Protocol

# Run sanitization check
if [ -f ".claude/scripts/pre-commit-sanitize.sh" ]; then
    bash .claude/scripts/pre-commit-sanitize.sh
    exit $?
else
    echo "Warning: Sanitization script not found"
    exit 0
fi
EOF

chmod +x "$HOOKS_DIR/pre-commit"
echo "  ✓ Installed pre-commit hook"

# Pre-push hook (extra safety)
cat > "$HOOKS_DIR/pre-push" << 'EOF'
#!/bin/bash
# Auto-generated by Claude Bootstrap Protocol

echo "Running pre-push checks..."

# Run full validation
if [ -f ".claude/scripts/validate-all.sh" ]; then
    bash .claude/scripts/validate-all.sh
fi

# Run sanitization again
if [ -f ".claude/scripts/pre-commit-sanitize.sh" ]; then
    bash .claude/scripts/pre-commit-sanitize.sh
fi

exit $?
EOF

chmod +x "$HOOKS_DIR/pre-push"
echo "  ✓ Installed pre-push hook"

echo ""
echo "Git hooks installed successfully!"
echo ""
echo "Hooks will run automatically on:"
echo "  - git commit (sanitization check)"
echo "  - git push (full validation + sanitization)"
echo ""
echo "To bypass (not recommended): git commit --no-verify"
