#!/bin/bash
# Protocol initialization script
# Sets up Claude Bootstrap Protocol for a project

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROTOCOL_DIR="$(dirname "$SCRIPT_DIR")"

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Claude Bootstrap Protocol Initialization${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""

# Check if target directory provided
TARGET_DIR="${1:-.}"
TARGET_DIR="$(cd "$TARGET_DIR" && pwd)"

echo "Target directory: $TARGET_DIR"
echo ""

# Detect project type
echo -e "${BLUE}Detecting project type...${NC}"

PROJECT_TYPE="unknown"
LANGUAGES=()
BUILD_CMD=""
TEST_CMD=""
LINT_CMD=""

# Check for package.json (Node.js)
if [ -f "$TARGET_DIR/package.json" ]; then
  PROJECT_TYPE="node"
  LANGUAGES+=("javascript" "typescript")
  BUILD_CMD="npm run build"
  TEST_CMD="npm test"
  LINT_CMD="npm run lint"
  echo -e "${GREEN}✓${NC} Detected Node.js project"
fi

# Check for requirements.txt (Python)
if [ -f "$TARGET_DIR/requirements.txt" ] || [ -f "$TARGET_DIR/setup.py" ] || [ -f "$TARGET_DIR/pyproject.toml" ]; then
  PROJECT_TYPE="python"
  LANGUAGES+=("python")
  TEST_CMD="pytest"
  LINT_CMD="flake8 ."
  echo -e "${GREEN}✓${NC} Detected Python project"
fi

# Check for Cargo.toml (Rust)
if [ -f "$TARGET_DIR/Cargo.toml" ]; then
  PROJECT_TYPE="rust"
  LANGUAGES+=("rust")
  BUILD_CMD="cargo build"
  TEST_CMD="cargo test"
  LINT_CMD="cargo clippy"
  echo -e "${GREEN}✓${NC} Detected Rust project"
fi

# Check for go.mod (Go)
if [ -f "$TARGET_DIR/go.mod" ]; then
  PROJECT_TYPE="go"
  LANGUAGES+=("go")
  BUILD_CMD="go build ./..."
  TEST_CMD="go test ./..."
  LINT_CMD="golint ./..."
  echo -e "${GREEN}✓${NC} Detected Go project"
fi

echo ""
echo "Project type: $PROJECT_TYPE"
echo "Languages: ${LANGUAGES[*]}"
echo ""

# Create .claude directory
CLAUDE_DIR="$TARGET_DIR/.claude"
mkdir -p "$CLAUDE_DIR"
mkdir -p "$CLAUDE_DIR/hooks"
mkdir -p "$CLAUDE_DIR/commands"
mkdir -p "$CLAUDE_DIR/agents"
mkdir -p "$CLAUDE_DIR/skills"
mkdir -p "$CLAUDE_DIR/memory"

echo -e "${GREEN}✓${NC} Created .claude directory structure"

# Copy protocol files if not already present
if [ ! -f "$CLAUDE_DIR/settings.json" ]; then
  cp "$PROTOCOL_DIR/.claude/settings.json" "$CLAUDE_DIR/settings.json"
  echo -e "${GREEN}✓${NC} Created settings.json"
fi

# Create CLAUDE.md if not exists
if [ ! -f "$TARGET_DIR/CLAUDE.md" ]; then
  cat > "$TARGET_DIR/CLAUDE.md" << EOF
# Project Configuration

Auto-generated by Claude Bootstrap Protocol.

## Build Commands

- Build: ${BUILD_CMD:-"Not detected"}
- Test: ${TEST_CMD:-"Not detected"}
- Lint: ${LINT_CMD:-"Not detected"}

## Project Type

${PROJECT_TYPE}

## Languages

${LANGUAGES[*]}

## Notes

Add project-specific notes here.
EOF
  echo -e "${GREEN}✓${NC} Created CLAUDE.md"
else
  echo -e "${YELLOW}⚠${NC} CLAUDE.md already exists, skipping"
fi

# Create .mcp.json if not exists
if [ ! -f "$TARGET_DIR/.mcp.json" ]; then
  cat > "$TARGET_DIR/.mcp.json" << EOF
{
  "mcpServers": {
    "memory": {
      "command": "node",
      "args": [".claude/mcp/memory-server/dist/index.js"],
      "env": {
        "MEMORY_PATH": ".claude/memory"
      }
    }
  }
}
EOF
  echo -e "${GREEN}✓${NC} Created .mcp.json"
fi

# Initialize memory
TIMESTAMP=$(date -Iseconds)
echo "{\"entries\":[],\"updated\":\"$TIMESTAMP\"}" > "$CLAUDE_DIR/memory/protocol-state.json"
echo -e "${GREEN}✓${NC} Initialized memory"

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Protocol initialization complete!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Next steps:"
echo "1. Review and customize CLAUDE.md"
echo "2. Run /validate to check configuration"
echo "3. Build the MCP server: cd .claude/mcp/memory-server && npm install && npm run build"
